### ISSUE TITLE
Grade Axes

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/variable-type-tools#9]
Combine xopq and xtra

**Comment by davelab6** [comment]
I'm reopening this as today on the site, the Amstelvar Alpha shows how opsz, wght and wdth are blended, but not GRAD - and demonstrating GRAD is made by blending XOPQ and XTRA "against each other" is now urgently important :)

**Comment by dberlow** [comment]
I think there are a number of ways to get from axes to grade.

I’m very sure Amstelvar was made from wdths and wghts of opszes — Remembering that it is grades of those three that people are interested in. 

I am also certain, that because of the serifs, there was hand tuning at the end.

Why?

On Apr 19, 2019, at 4:25 PM, Dave Crossland <notifications@github.com> wrote:

I'm reopening this as today on the site, the Amstelvar Alpha shows how opsz, wght and wdth are blended, but not GRAD - and demonstrating GRAD is made by blending XOPQ and XTRA "against each other" is now urgently important :)

**Comment by dberlow** [comment]
Google has requested a change to TypeTools displaying Amstelvar Alpha.

The request is:
1. When the grade slider is moved, 
2. show how YOPQ, XTRA and XOPQ change accordingly. 
3. this is “immediate.”

Relevant values From:
AmstelvarAlpha/sources/AmstelvarAlpha-Blended/sources/Alpha/
Default , YOPQ=62, XOPQ=88, XTRA=402
GRAD max , YOPQ=62, XOPQ=250, XTRA=460
GRAD  min  ,YOPQ=25, XOPQ=25, XTRA=490

Let me know if this is soon doable, thanks.

**Comment by chrissam42** [comment]
Can do quickly once I figure out where the right font file is. The Alpha on type tools has GRAD range 88–150 with the default at 88. Where is the newer Alpha?

**Comment by dberlow** [comment]
The measurements I provided came from the Source files as the repo linked to?
Santiago, are those the right sources?

On Apr 20, 2019, at 7:48 PM, Chris Lewis <notifications@github.com> wrote:

Can do quickly once I figure out where the right font file is. The Alpha on type tools has GRAD range 88–150 with the default at 88. Where is the newer Alpha?

**Comment by chrissam42** [comment]
I think there is a separate Alpha repo that i am not on? I have an
Amstelvar repo but it doesn’t have the folders you listed.

**Comment by dberlow** [comment]
You can get to here?
https://github.com/TypeNetwork/AmstelvarAlpha

On Apr 21, 2019, at 10:39 AM, Chris Lewis <notifications@github.com> wrote:

I think there is a separate Alpha repo that i am not on? I have an
Amstelvar repo but it doesn’t have the folders you listed.

**Comment by chrissam42** [comment]
Okay got it, I will move some things around and update all the parametric relations.

**Comment by chrissam42** [comment]
Hmm I'm still confused. I've looked through all the design spaces in all the sources in AmstelvarAlpha repo, and I still don't see where these values are coming from. They all have the minimum Grade being the default.

I see Santiago wasn't on this repo either! I've added him and will tag him when he joins.

**Comment by dberlow** [comment]
They are all the default because they are following the spec. 

We are adding data about the ga]rade axes to our JavaScript that moves the sliders. That’s why I measured and gave you the accurate values.

Santiago created this repo, I think.

On Apr 21, 2019, at 5:21 PM, Chris Lewis <notifications@github.com> wrote:

Hmm I'm still confused. I've looked through all the design spaces in all the sources in AmstelvarAlpha repo, and I still don't see where these values are coming from. They all have the minimum Grade being the default.

I see Santiago wasn't on this repo either! I've added him and will tag him when he joins.
